sudo: required
dist: trusty
language: php

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # Return to the Travis build directory.
  - cd -
  # Copy Travis composer.json to the build directory.
  - cp ./lemberg/draft/.travis.composer.json ./composer.json
  # Composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
  # Tweak PHP configuration.
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
  # Build the code base.
  - composer install --no-interaction --no-progress --no-suggest
  # Add Composer's local bin directory to the PATH.
  - export PATH="$HOME/.composer/vendor/bin:$(readlink -e ./vendor/bin):$PATH"
  # Installation profile must exist within drupal codebase. Symlink it.
  - mkdir docroot/profiles
  - ln -s $(readlink -e $TRAVIS_BUILD_DIR) docroot/profiles/draft

script:
  - drush site-install --db-url=mysql://drupal:drupal@localhost/drupal --account-name=admin --account-pass=admin -r ./docroot --yes

matrix:
  fast_finish: true
