---
version: ~> 1.0

branches:
  only:
    - /^\d+\.x\.x$/
    - /^\d+\.\d+\.\d+[-a-z0-9]*$/

os: linux
dist: xenial

services:
  - mysql

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

language: php

jobs:
  fast_finish: true

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  # Tweak PHP configuration.
  - phpenv config-rm xdebug.ini
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"

install:
  # Get back to the home directory.
  - cd $TRAVIS_HOME
  # Create a new Drupal project using the recommended-project template.
  - composer create-project drupal/recommended-project project
  - cd project
  - composer config repositories.draft path $TRAVIS_BUILD_DIR
  - composer config extra.composer-exit-on-patch-failure true
  - composer config extra.enable-patching true
  - composer require zaporylie/composer-drupal-optimizations:^1.1 --dev
  - composer require drush/drush:^10
  - composer require lemberg/draft @dev

script:
  - ./vendor/bin/drush site:install --db-url=mysql://drupal:drupal@localhost/drupal --account-name=admin --account-pass=admin -root ./web --yes
